### ISSUE TITLE
Can't use if pages folder inside src folder

### ISSUE THREAD

**Issue by IRediTOTO** [Lindeneg/generate-next-links#37]
```
npx generate-next-links -P /src
npx generate-next-links -P src
npx generate-next-links -P /src
npx generate-next-links -P C:\Job\test\src
```
I tried those but not work :\

**Comment by Lindeneg** [comment]
Hi @IRediTOTO 

1) Do you get any errors?

2) What folders are inside your src folder? Could you give me like a `tree` of it or something similar?

3) Try to run with the ´-V´ which should print out more debugging information. 

Note, it may be a windows specific problem, I've only run this program on mac/linux but whatever it is, we'll find it, and if it is a windows specific issue, I'll fix it.

**Comment by Lindeneg** [comment]
Hi again,

This is a windows specific issue, I can replicate it on a windows machine. I also know what the issue is. I should utilize the `path` standard library to resolve paths. The paths I use internally are compatible with linux/mac, not windows. 

As an alternative until a fix is released, you can use windows-linux-subsystem ([WSL](https://docs.microsoft.com/en-us/windows/wsl/install)) to generate the links.

**Comment by Lindeneg** [comment]
Issue should now be resolved. Try running with the `@latest` option to ensure you get the last published version, if you still encounter this problem.

Thanks again for opening the issue.
